CREATE TABLE tb_jenis_data_opd(
    id INT PRIMARY KEY AUTO_INCREMENT,
    kode_opd VARCHAR(255),
    nama_opd VARCHAR(255),
    jenis_data VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;