// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"alurkerjaService/app"
	"alurkerjaService/controller"
	"alurkerjaService/repository"
	"alurkerjaService/service"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
)

// Injectors from injector.go:

func InitializedServer() *echo.Echo {
	jenisDataRepositoryImpl := repository.NewJenisDataRepositoryImpl()
	db := app.GetConnection()
	v := _wireValue
	validate := validator.New(v...)
	jenisDataServiceImpl := service.NewJenisDataServiceImpl(jenisDataRepositoryImpl, db, validate)
	jenisDataControllerImpl := controller.NewJenisDataControllerImpl(jenisDataServiceImpl)
	dataKinerjaPemdaRepositoryImpl := repository.NewDataKinerjaPemdaRepositoryImpl()
	dataKinerjaPemdaServiceImpl := service.NewDataKinerjaPemdaServiceImpl(dataKinerjaPemdaRepositoryImpl, db, validate, jenisDataRepositoryImpl)
	dataKinerjaPemdaControllerImpl := controller.NewDataKinerjaPemdaControllerImpl(dataKinerjaPemdaServiceImpl)
	dataKinerjaOpdRepositoryImpl := repository.NewDataKinerjaOpdRepositoryImpl()
	dataKinerjaOpdServiceImpl := service.NewDataKinerjaOpdServiceImpl(dataKinerjaOpdRepositoryImpl, db, validate, jenisDataRepositoryImpl)
	dataKinerjaOpdControllerImpl := controller.NewDataKinerjaOpdControllerImpl(dataKinerjaOpdServiceImpl)
	echoEcho := app.NewRouter(jenisDataControllerImpl, dataKinerjaPemdaControllerImpl, dataKinerjaOpdControllerImpl)
	return echoEcho
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var jenisDataSet = wire.NewSet(repository.NewJenisDataRepositoryImpl, wire.Bind(new(repository.JenisDataRepository), new(*repository.JenisDataRepositoryImpl)), service.NewJenisDataServiceImpl, wire.Bind(new(service.JenisDataService), new(*service.JenisDataServiceImpl)), controller.NewJenisDataControllerImpl, wire.Bind(new(controller.JenisDataController), new(*controller.JenisDataControllerImpl)))

var dataKinerjaPemdaSet = wire.NewSet(repository.NewDataKinerjaPemdaRepositoryImpl, wire.Bind(new(repository.DataKinerjaPemdaRepository), new(*repository.DataKinerjaPemdaRepositoryImpl)), service.NewDataKinerjaPemdaServiceImpl, wire.Bind(new(service.DataKinerjaPemdaService), new(*service.DataKinerjaPemdaServiceImpl)), controller.NewDataKinerjaPemdaControllerImpl, wire.Bind(new(controller.DataKinerjaPemdaController), new(*controller.DataKinerjaPemdaControllerImpl)))

var dataKinerjaOpdSet = wire.NewSet(repository.NewDataKinerjaOpdRepositoryImpl, wire.Bind(new(repository.DataKinerjaOpdRepository), new(*repository.DataKinerjaOpdRepositoryImpl)), service.NewDataKinerjaOpdServiceImpl, wire.Bind(new(service.DataKinerjaOpdService), new(*service.DataKinerjaOpdServiceImpl)), controller.NewDataKinerjaOpdControllerImpl, wire.Bind(new(controller.DataKinerjaOpdController), new(*controller.DataKinerjaOpdControllerImpl)))
