// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/datakinerjaopd": {
            "post": {
                "description": "Create new Data Kinerja OPD with targets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja OPD"
                ],
                "summary": "Create Data Kinerja OPD",
                "parameters": [
                    {
                        "description": "Data Kinerja OPD Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.DataKinerjaOpdCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.DataKinerjaOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/datakinerjaopd/detail/{id}": {
            "get": {
                "description": "Get Data Kinerja OPD detail by ID including targets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja OPD"
                ],
                "summary": "Get Data Kinerja OPD by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Data Kinerja OPD ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.DataKinerjaOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/datakinerjaopd/list/{kode_opd}/{jenis_data_id}": {
            "get": {
                "description": "Get list of Data Kinerja OPD filtered by jenis data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja OPD"
                ],
                "summary": "List Data Kinerja OPD",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kode_opd",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Jenis Data ID",
                        "name": "jenis_data_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.DataKinerjaOpdResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/datakinerjaopd/{id}": {
            "put": {
                "description": "Update existing Data Kinerja OPD by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja OPD"
                ],
                "summary": "Update Data Kinerja OPD",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Data Kinerja OPD ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Kinerja OPD Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.DataKinerjaOpdUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.DataKinerjaOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Data Kinerja OPD by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja OPD"
                ],
                "summary": "Delete Data Kinerja OPD",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Data Kinerja OPD ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/datakinerjapemda": {
            "post": {
                "description": "Create new Data Kinerja Pemda with targets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja Pemda"
                ],
                "summary": "Create Data Kinerja Pemda",
                "parameters": [
                    {
                        "description": "Data Kinerja Pemda Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.DataKinerjaPemdaCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.DataKinerjaPemdaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/datakinerjapemda/detail/{id}": {
            "get": {
                "description": "Get Data Kinerja Pemda detail by ID including targets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja Pemda"
                ],
                "summary": "Get Data Kinerja Pemda by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Data Kinerja Pemda ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.DataKinerjaPemdaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/datakinerjapemda/list/{jenis_data_id}": {
            "get": {
                "description": "Get list of Data Kinerja Pemda filtered by jenis data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja Pemda"
                ],
                "summary": "List Data Kinerja Pemda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jenis Data ID",
                        "name": "jenis_data_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.DataKinerjaPemdaResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/datakinerjapemda/{id}": {
            "put": {
                "description": "Update existing Data Kinerja Pemda by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja Pemda"
                ],
                "summary": "Update Data Kinerja Pemda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Data Kinerja Pemda ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Kinerja Pemda Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.DataKinerjaPemdaUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.DataKinerjaPemdaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Data Kinerja Pemda by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Kinerja Pemda"
                ],
                "summary": "Delete Data Kinerja Pemda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Data Kinerja Pemda ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/jenisdata": {
            "get": {
                "description": "Get list of all Jenis Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jenis Data"
                ],
                "summary": "List All Jenis Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.JenisDataResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Jenis Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jenis Data"
                ],
                "summary": "Create Jenis Data",
                "parameters": [
                    {
                        "description": "Jenis Data Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.JenisDataCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JenisDataResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/jenisdata/{id}": {
            "get": {
                "description": "Get Jenis Data detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jenis Data"
                ],
                "summary": "Get Jenis Data by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jenis Data ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JenisDataResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update existing Jenis Data by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jenis Data"
                ],
                "summary": "Update Jenis Data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jenis Data ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Jenis Data Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.JenisDataUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JenisDataResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/jenisdataopd": {
            "post": {
                "description": "Create new Jenis Data OPD",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jenis Data OPD"
                ],
                "summary": "Create Jenis Data OPD",
                "parameters": [
                    {
                        "description": "Jenis Data OPD Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.JenisDataOpdCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JenisDataOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/jenisdataopd/detail/{id}": {
            "get": {
                "description": "Get Jenis Data OPD detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jenis Data OPD"
                ],
                "summary": "Get Jenis Data OPD by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jenis Data OPD ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JenisDataOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/jenisdataopd/list/{kode_opd}": {
            "get": {
                "description": "Get list of all Jenis Data OPD",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jenis Data OPD"
                ],
                "summary": "List All Jenis Data OPD",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kode_opd",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.JenisDataOpdResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/jenisdataopd/{id}": {
            "put": {
                "description": "Update existing Jenis Data OPD by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jenis Data OPD"
                ],
                "summary": "Update Jenis Data OPD",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jenis Data OPD ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Jenis Data OPD Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.JenisDataOpdUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JenisDataOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.DataKinerjaOpdCreateRequest": {
            "type": "object",
            "required": [
                "instansi_produsen_data",
                "jenis_data_id",
                "kode_opd",
                "nama_data",
                "rumus_perhitungan",
                "sumber_data",
                "target"
            ],
            "properties": {
                "instansi_produsen_data": {
                    "type": "string"
                },
                "jenis_data_id": {
                    "type": "integer"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_data": {
                    "type": "string"
                },
                "rumus_perhitungan": {
                    "type": "string"
                },
                "sumber_data": {
                    "type": "string"
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetCreateRequest"
                    }
                }
            }
        },
        "web.DataKinerjaOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "instansi_produsen_data": {
                    "type": "string"
                },
                "jenis_data": {
                    "type": "string"
                },
                "jenis_data_id": {
                    "type": "integer"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_data": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                },
                "rumus_perhitungan": {
                    "type": "string"
                },
                "sumber_data": {
                    "type": "string"
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetResponse"
                    }
                }
            }
        },
        "web.DataKinerjaOpdUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "instansi_produsen_data",
                "jenis_data_id",
                "kode_opd",
                "nama_data",
                "rumus_perhitungan",
                "sumber_data",
                "target"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "instansi_produsen_data": {
                    "type": "string"
                },
                "jenis_data_id": {
                    "type": "integer"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_data": {
                    "type": "string"
                },
                "rumus_perhitungan": {
                    "type": "string"
                },
                "sumber_data": {
                    "type": "string"
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetUpdateRequest"
                    }
                }
            }
        },
        "web.DataKinerjaPemdaCreateRequest": {
            "type": "object",
            "required": [
                "instansi_produsen_data",
                "jenis_data_id",
                "nama_data",
                "rumus_perhitungan",
                "sumber_data",
                "target"
            ],
            "properties": {
                "instansi_produsen_data": {
                    "type": "string"
                },
                "jenis_data_id": {
                    "type": "integer"
                },
                "keterangan": {
                    "type": "string"
                },
                "nama_data": {
                    "type": "string"
                },
                "rumus_perhitungan": {
                    "type": "string"
                },
                "sumber_data": {
                    "type": "string"
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetCreateRequest"
                    }
                }
            }
        },
        "web.DataKinerjaPemdaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "instansi_produsen_data": {
                    "type": "string"
                },
                "jenis_data": {
                    "type": "string"
                },
                "jenis_data_id": {
                    "type": "integer"
                },
                "keterangan": {
                    "type": "string"
                },
                "nama_data": {
                    "type": "string"
                },
                "rumus_perhitungan": {
                    "type": "string"
                },
                "sumber_data": {
                    "type": "string"
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetResponse"
                    }
                }
            }
        },
        "web.DataKinerjaPemdaUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "instansi_produsen_data",
                "jenis_data_id",
                "nama_data",
                "rumus_perhitungan",
                "sumber_data",
                "target"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "instansi_produsen_data": {
                    "type": "string"
                },
                "jenis_data_id": {
                    "type": "integer"
                },
                "keterangan": {
                    "type": "string"
                },
                "nama_data": {
                    "type": "string"
                },
                "rumus_perhitungan": {
                    "type": "string"
                },
                "sumber_data": {
                    "type": "string"
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetUpdateRequest"
                    }
                }
            }
        },
        "web.JenisDataCreateRequest": {
            "type": "object",
            "required": [
                "jenis_data"
            ],
            "properties": {
                "jenis_data": {
                    "type": "string"
                }
            }
        },
        "web.JenisDataOpdCreateRequest": {
            "type": "object",
            "required": [
                "jenis_data",
                "kode_opd",
                "nama_opd"
            ],
            "properties": {
                "jenis_data": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                }
            }
        },
        "web.JenisDataOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jenis_data": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                }
            }
        },
        "web.JenisDataOpdUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "jenis_data",
                "kode_opd",
                "nama_opd"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jenis_data": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                }
            }
        },
        "web.JenisDataResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jenis_data": {
                    "type": "string"
                }
            }
        },
        "web.JenisDataUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "jenis_data"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jenis_data": {
                    "type": "string"
                }
            }
        },
        "web.TargetCreateRequest": {
            "type": "object",
            "required": [
                "satuan",
                "tahun",
                "target"
            ],
            "properties": {
                "satuan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "web.TargetResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "satuan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "web.TargetUpdateRequest": {
            "type": "object",
            "required": [
                "satuan",
                "tahun",
                "target"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "satuan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "web.WebResponse": {
            "description": "Web Response",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "${PROD_HOSTNAME}",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Alur Kerja Service API",
	Description:      "API For Alur Kerja Services",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
