basePath: /
definitions:
  web.DataKinerjaOpdCreateRequest:
    properties:
      instansi_produsen_data:
        type: string
      jenis_data_id:
        type: integer
      keterangan:
        type: string
      kode_opd:
        type: string
      nama_data:
        type: string
      nama_opd:
        type: string
      rumus_perhitungan:
        type: string
      sumber_data:
        type: string
      target:
        items:
          $ref: '#/definitions/web.TargetCreateRequest'
        type: array
    required:
    - instansi_produsen_data
    - jenis_data_id
    - kode_opd
    - nama_data
    - nama_opd
    - rumus_perhitungan
    - sumber_data
    - target
    type: object
  web.DataKinerjaOpdResponse:
    properties:
      id:
        type: integer
      instansi_produsen_data:
        type: string
      jenis_data:
        type: string
      jenis_data_id:
        type: integer
      keterangan:
        type: string
      kode_opd:
        type: string
      nama_data:
        type: string
      nama_opd:
        type: string
      rumus_perhitungan:
        type: string
      sumber_data:
        type: string
      target:
        items:
          $ref: '#/definitions/web.TargetResponse'
        type: array
    type: object
  web.DataKinerjaOpdUpdateRequest:
    properties:
      id:
        type: integer
      instansi_produsen_data:
        type: string
      jenis_data_id:
        type: integer
      keterangan:
        type: string
      kode_opd:
        type: string
      nama_data:
        type: string
      nama_opd:
        type: string
      rumus_perhitungan:
        type: string
      sumber_data:
        type: string
      target:
        items:
          $ref: '#/definitions/web.TargetUpdateRequest'
        type: array
    required:
    - id
    - instansi_produsen_data
    - jenis_data_id
    - kode_opd
    - nama_data
    - nama_opd
    - rumus_perhitungan
    - sumber_data
    - target
    type: object
  web.DataKinerjaPemdaCreateRequest:
    properties:
      instansi_produsen_data:
        type: string
      jenis_data_id:
        type: integer
      keterangan:
        type: string
      nama_data:
        type: string
      rumus_perhitungan:
        type: string
      sumber_data:
        type: string
      target:
        items:
          $ref: '#/definitions/web.TargetCreateRequest'
        type: array
    required:
    - instansi_produsen_data
    - jenis_data_id
    - nama_data
    - rumus_perhitungan
    - sumber_data
    - target
    type: object
  web.DataKinerjaPemdaResponse:
    properties:
      id:
        type: integer
      instansi_produsen_data:
        type: string
      jenis_data:
        type: string
      jenis_data_id:
        type: integer
      keterangan:
        type: string
      nama_data:
        type: string
      rumus_perhitungan:
        type: string
      sumber_data:
        type: string
      target:
        items:
          $ref: '#/definitions/web.TargetResponse'
        type: array
    type: object
  web.DataKinerjaPemdaUpdateRequest:
    properties:
      id:
        type: integer
      instansi_produsen_data:
        type: string
      jenis_data_id:
        type: integer
      keterangan:
        type: string
      nama_data:
        type: string
      rumus_perhitungan:
        type: string
      sumber_data:
        type: string
      target:
        items:
          $ref: '#/definitions/web.TargetUpdateRequest'
        type: array
    required:
    - id
    - instansi_produsen_data
    - jenis_data_id
    - nama_data
    - rumus_perhitungan
    - sumber_data
    - target
    type: object
  web.JenisDataCreateRequest:
    properties:
      jenis_data:
        type: string
    required:
    - jenis_data
    type: object
  web.JenisDataResponse:
    properties:
      id:
        type: integer
      jenis_data:
        type: string
    type: object
  web.JenisDataUpdateRequest:
    properties:
      id:
        type: integer
      jenis_data:
        type: string
    required:
    - id
    - jenis_data
    type: object
  web.TargetCreateRequest:
    properties:
      satuan:
        type: string
      tahun:
        type: string
      target:
        type: string
    required:
    - satuan
    - tahun
    - target
    type: object
  web.TargetResponse:
    properties:
      id:
        type: integer
      satuan:
        type: string
      tahun:
        type: string
      target:
        type: string
    type: object
  web.TargetUpdateRequest:
    properties:
      id:
        type: integer
      satuan:
        type: string
      tahun:
        type: string
      target:
        type: string
    required:
    - satuan
    - tahun
    - target
    type: object
  web.WebResponse:
    description: Web Response
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: ${HOST}:${PORT}
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API For Alur Kerja Services
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Alur Kerja Service API
  version: "1.0"
paths:
  /datakinerjaopd:
    post:
      consumes:
      - application/json
      description: Create new Data Kinerja OPD with targets
      parameters:
      - description: Data Kinerja OPD Create Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/web.DataKinerjaOpdCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.DataKinerjaOpdResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Create Data Kinerja OPD
      tags:
      - Data Kinerja OPD
  /datakinerjaopd/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Data Kinerja OPD by ID
      parameters:
      - description: Data Kinerja OPD ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Delete Data Kinerja OPD
      tags:
      - Data Kinerja OPD
    put:
      consumes:
      - application/json
      description: Update existing Data Kinerja OPD by ID
      parameters:
      - description: Data Kinerja OPD ID
        in: path
        name: id
        required: true
        type: integer
      - description: Data Kinerja OPD Update Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/web.DataKinerjaOpdUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.DataKinerjaOpdResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Update Data Kinerja OPD
      tags:
      - Data Kinerja OPD
  /datakinerjaopd/detail/{id}:
    get:
      consumes:
      - application/json
      description: Get Data Kinerja OPD detail by ID including targets
      parameters:
      - description: Data Kinerja OPD ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.DataKinerjaOpdResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Get Data Kinerja OPD by ID
      tags:
      - Data Kinerja OPD
  /datakinerjaopd/list/{kode_opd}/{jenis_data_id}:
    get:
      consumes:
      - application/json
      description: Get list of Data Kinerja OPD filtered by jenis data
      parameters:
      - description: Kode OPD
        in: path
        name: kode_opd
        required: true
        type: string
      - description: Jenis Data ID
        in: path
        name: jenis_data_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/web.DataKinerjaOpdResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: List Data Kinerja OPD
      tags:
      - Data Kinerja OPD
  /datakinerjapemda:
    post:
      consumes:
      - application/json
      description: Create new Data Kinerja Pemda with targets
      parameters:
      - description: Data Kinerja Pemda Create Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/web.DataKinerjaPemdaCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.DataKinerjaPemdaResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Create Data Kinerja Pemda
      tags:
      - Data Kinerja Pemda
  /datakinerjapemda/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Data Kinerja Pemda by ID
      parameters:
      - description: Data Kinerja Pemda ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Delete Data Kinerja Pemda
      tags:
      - Data Kinerja Pemda
    put:
      consumes:
      - application/json
      description: Update existing Data Kinerja Pemda by ID
      parameters:
      - description: Data Kinerja Pemda ID
        in: path
        name: id
        required: true
        type: integer
      - description: Data Kinerja Pemda Update Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/web.DataKinerjaPemdaUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.DataKinerjaPemdaResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Update Data Kinerja Pemda
      tags:
      - Data Kinerja Pemda
  /datakinerjapemda/detail/{id}:
    get:
      consumes:
      - application/json
      description: Get Data Kinerja Pemda detail by ID including targets
      parameters:
      - description: Data Kinerja Pemda ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.DataKinerjaPemdaResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Get Data Kinerja Pemda by ID
      tags:
      - Data Kinerja Pemda
  /datakinerjapemda/list/{jenis_data_id}:
    get:
      consumes:
      - application/json
      description: Get list of Data Kinerja Pemda filtered by jenis data
      parameters:
      - description: Jenis Data ID
        in: path
        name: jenis_data_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/web.DataKinerjaPemdaResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: List Data Kinerja Pemda
      tags:
      - Data Kinerja Pemda
  /jenisdata:
    get:
      consumes:
      - application/json
      description: Get list of all Jenis Data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/web.JenisDataResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: List All Jenis Data
      tags:
      - Jenis Data
    post:
      consumes:
      - application/json
      description: Create new Jenis Data
      parameters:
      - description: Jenis Data Create Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/web.JenisDataCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.JenisDataResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Create Jenis Data
      tags:
      - Jenis Data
  /jenisdata/{id}:
    get:
      consumes:
      - application/json
      description: Get Jenis Data detail by ID
      parameters:
      - description: Jenis Data ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.JenisDataResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Get Jenis Data by ID
      tags:
      - Jenis Data
    put:
      consumes:
      - application/json
      description: Update existing Jenis Data by ID
      parameters:
      - description: Jenis Data ID
        in: path
        name: id
        required: true
        type: integer
      - description: Jenis Data Update Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/web.JenisDataUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/web.JenisDataResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Update Jenis Data
      tags:
      - Jenis Data
schemes:
- http
- https
swagger: "2.0"
